Change koji workaround to allow mockbuild to pass
This proposal changes the way work-around for the
rhbz#1406383 is applied from installing older
version of koji, which have installation conflicts
to the work-around suggested in the rhbz.

 - Add ca-certificate to allow mockbuild to pass

 - If there is python-request or python-certifi
   installed on the system, then ca-bundle.crt
   needs to be passed as environment variable
   for mockbuild to success.

Change-Id: Ibc67ac169ae3ffb39337cbb61e3ae0300edc62f9

diff --git a/roles/patch_rpm/tasks/main.yml b/roles/patch_rpm/tasks/main.yml
--- a/roles/patch_rpm/tasks/main.yml
+++ b/roles/patch_rpm/tasks/main.yml
@@ -24,14 +24,6 @@
   tags:
     - skip_ansible_lint
 
-# Koji 1.11 will cause 'rdopkg patch' to fail
-# See the following bug: https://bugzilla.redhat.com/show_bug.cgi?id=1406383
-- name: Install Koji 1.10
-  become: yes
-  yum:
-    name="https://copr-be.cloud.fedoraproject.org/results/abregman/el7-rhos10-test-deps/epel-7-x86_64/00602353-koji/koji-1.10.1-3.el7.centos.noarch.rpm"
-    state=present
-
 # Although pyrpkg pulled by rhpkg, we install it directly because at the moment, an older
 # version of pyrpkg is pulled (1.40) while we need a newer version (1.43)
 - name: Install packages required for patching
@@ -41,6 +33,7 @@
     state=present
   with_items:
     - 'pyrpkg'
+    - 'ca-certificates'
     - 'createrepo'
     - 'python-pip'
     - 'python-cryptography'
@@ -143,10 +136,11 @@
 # Now that the repo is patched, generate RPMs from it
 - name: Build new RPM from patched dist-git repo
   shell: |
-    set -exo pipefail
-    # Workaround for: Could not execute mockbuild: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
-    export PYTHONHTTPSVERIFY=0
-    rdopkg mockbuild
+    set -exo pipefail;
+    # Workaround for rhbz#1406383: Could not execute mockbuild: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
+    export PYTHONHTTPSVERIFY=0;
+    export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt;
+    rdopkg mockbuild;
   args:
     chdir: "{{ tmp_dir }}/dist-git/{{ component_dist_git_name }}"
   register: rpm_mockbuild
